create table addres (id bigint not null auto_increment, city varchar(255), postal_code varchar(255), street varchar(255), addres_id bigint, primary key (id)) engine=InnoDB;
create table person (id bigint not null auto_increment, first_name varchar(255), last_name varchar(255), primary key (id)) engine=InnoDB;
alter table addres add constraint FKfop5g48yrqe3dq6hhkb933xsf foreign key (addres_id) references person (id);
create table addres (id bigint not null auto_increment, city varchar(255), postal_code varchar(255), street varchar(255), addres_id bigint, primary key (id)) engine=InnoDB;
create table person (id bigint not null auto_increment, first_name varchar(255), last_name varchar(255), primary key (id)) engine=InnoDB;
alter table addres add constraint FKfop5g48yrqe3dq6hhkb933xsf foreign key (addres_id) references person (id);
create table addres (id bigint not null auto_increment, city varchar(255), postal_code varchar(255), street varchar(255), addres_id bigint, primary key (id)) engine=InnoDB;
create table person (id bigint not null auto_increment, first_name varchar(255), last_name varchar(255), primary key (id)) engine=InnoDB;
alter table addres add constraint FKfop5g48yrqe3dq6hhkb933xsf foreign key (addres_id) references person (id);
create table addres (id bigint not null auto_increment, city varchar(255), postal_code varchar(255), street varchar(255), addres_id bigint, primary key (id)) engine=InnoDB;
create table person (id bigint not null auto_increment, first_name varchar(255), last_name varchar(255), primary key (id)) engine=InnoDB;
alter table addres add constraint FKfop5g48yrqe3dq6hhkb933xsf foreign key (addres_id) references person (id);
create table addres (id bigint not null auto_increment, city varchar(255), postal_code varchar(255), street varchar(255), addres_id bigint, primary key (id)) engine=InnoDB;
create table person (id bigint not null auto_increment, first_name varchar(255), last_name varchar(255), primary key (id)) engine=InnoDB;
alter table addres add constraint FKfop5g48yrqe3dq6hhkb933xsf foreign key (addres_id) references person (id);
create table addres (id bigint not null auto_increment, city varchar(255), postal_code varchar(255), street varchar(255), addres_id bigint, primary key (id)) engine=InnoDB;
create table person (id bigint not null auto_increment, first_name varchar(255), last_name varchar(255), primary key (id)) engine=InnoDB;
alter table addres add constraint FKfop5g48yrqe3dq6hhkb933xsf foreign key (addres_id) references person (id);
create table addres (id bigint not null auto_increment, city varchar(255), postal_code varchar(255), street varchar(255), addres_id bigint, primary key (id)) engine=InnoDB;
create table person (id bigint not null auto_increment, first_name varchar(255), last_name varchar(255), primary key (id)) engine=InnoDB;
alter table addres add constraint FKfop5g48yrqe3dq6hhkb933xsf foreign key (addres_id) references person (id);
create table addres (id bigint not null auto_increment, city varchar(255), postal_code varchar(255), street varchar(255), addres_id bigint, primary key (id)) engine=InnoDB;
create table person (id bigint not null auto_increment, first_name varchar(255), last_name varchar(255), primary key (id)) engine=InnoDB;
alter table addres add constraint FKfop5g48yrqe3dq6hhkb933xsf foreign key (addres_id) references person (id);
create table addres (id bigint not null auto_increment, city varchar(255), postal_code varchar(255), street varchar(255), addres_id bigint, primary key (id)) engine=InnoDB;
create table person (id bigint not null auto_increment, first_name varchar(255), last_name varchar(255), primary key (id)) engine=InnoDB;
alter table addres add constraint FKfop5g48yrqe3dq6hhkb933xsf foreign key (addres_id) references person (id);
create table addres (id bigint not null auto_increment, city varchar(255), postal_code varchar(255), street varchar(255), addres_id bigint, primary key (id)) engine=InnoDB;
create table person (id bigint not null auto_increment, first_name varchar(255), last_name varchar(255), primary key (id)) engine=InnoDB;
alter table addres add constraint FKfop5g48yrqe3dq6hhkb933xsf foreign key (addres_id) references person (id);
create table addres (id bigint not null auto_increment, city varchar(255), postal_code varchar(255), street varchar(255), addres_id bigint, primary key (id)) engine=InnoDB;
create table person (id bigint not null auto_increment, first_name varchar(255), last_name varchar(255), primary key (id)) engine=InnoDB;
alter table addres add constraint FKfop5g48yrqe3dq6hhkb933xsf foreign key (addres_id) references person (id);
create table addres (id bigint not null auto_increment, city varchar(255), postal_code varchar(255), street varchar(255), addres_id bigint, primary key (id)) engine=InnoDB;
create table person (id bigint not null auto_increment, first_name varchar(255), last_name varchar(255), primary key (id)) engine=InnoDB;
alter table addres add constraint FKfop5g48yrqe3dq6hhkb933xsf foreign key (addres_id) references person (id);
