alter table addres drop foreign key FKfop5g48yrqe3dq6hhkb933xsf;
drop table if exists addres;
drop table if exists person;
alter table addres drop foreign key FKfop5g48yrqe3dq6hhkb933xsf;
drop table if exists addres;
drop table if exists person;
alter table addres drop foreign key FKfop5g48yrqe3dq6hhkb933xsf;
drop table if exists addres;
drop table if exists person;
alter table addres drop foreign key FKfop5g48yrqe3dq6hhkb933xsf;
drop table if exists addres;
drop table if exists person;
alter table addres drop foreign key FKfop5g48yrqe3dq6hhkb933xsf;
drop table if exists addres;
drop table if exists person;
alter table addres drop foreign key FKfop5g48yrqe3dq6hhkb933xsf;
drop table if exists addres;
drop table if exists person;
alter table addres drop foreign key FKfop5g48yrqe3dq6hhkb933xsf;
drop table if exists addres;
drop table if exists person;
alter table addres drop foreign key FKfop5g48yrqe3dq6hhkb933xsf;
drop table if exists addres;
drop table if exists person;
alter table addres drop foreign key FKfop5g48yrqe3dq6hhkb933xsf;
drop table if exists addres;
drop table if exists person;
alter table addres drop foreign key FKfop5g48yrqe3dq6hhkb933xsf;
drop table if exists addres;
drop table if exists person;
alter table addres drop foreign key FKfop5g48yrqe3dq6hhkb933xsf;
drop table if exists addres;
drop table if exists person;
alter table addres drop foreign key FKfop5g48yrqe3dq6hhkb933xsf;
drop table if exists addres;
drop table if exists person;
